### ISSUE TITLE
Skydio 2024-10-10 has been processing for a month

### ISSUE THREAD

**Issue by rrowlands** [terraframe/osmre-uav#412]
There's an upload process for that same collection that's been "uploading" since October17. I'm trying to help him delete the collection but it won't allow because "Cannot delete collection Skydio 2024-10-10 because it is currently in the middle of processing. Please wait until it is finished."

![image](https://github.com/user-attachments/assets/770c9925-afbd-4f5e-82d0-179dfb03aa02)

**Comment by rrowlands** [comment]
I found this error in the logs. I think it is the root cause error:

```
2024-10-17 14:38:17 ERROR Error occurred in 'handleUploadFinish'.
com.runwaysdk.session.InvalidSessionException: Session [a524a7cf7bcd4102b9ce4337d8] does not exist or has expired.
	at com.runwaysdk.session.BufferedSessionCache.getCache(BufferedSessionCache.java:60) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.session.CompositeSessionCache.getSession(CompositeSessionCache.java:312) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.session.SessionFacade.checkAccess(SessionFacade.java:292) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.session.AbstractRequestAspectState.checkEntityWritePermission(AbstractRequestAspectState.java:972) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.session.AbstractRequestAspectState.elementLockedByCheck(AbstractRequestAspectState.java:337) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.session.AbstractRequestManagement.ajc$before$com_runwaysdk_session_AbstractRequestManagement$17$de299a4a(AbstractRequestManagement.aj:486) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.business.Element.userLock(Element.java:356) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.business.Element.lock_aroundBody0(Element.java:389) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.business.Element.lock_aroundBody1$advice(Element.java:931) ~[runwaysdk-server-3.8.14.jar:?]
	at com.runwaysdk.business.Element.lock(Element.java:1) ~[runwaysdk-server-3.8.14.jar:?]
	at gov.geoplatform.uasdm.ImageryProcessingJob.processFiles(ImageryProcessingJob.java:156) ~[uasdm-server-1.3.0.jar:?]
	at gov.geoplatform.uasdm.service.ProjectManagementService.handleUploadFinish_aroundBody32(ProjectManagementService.java:651) ~[uasdm-server-1.3.0.jar:?]
	at gov.geoplatform.uasdm.service.ProjectManagementService.handleUploadFinish_aroundBody33$advice(ProjectManagementService.java:98) ~[uasdm-server-1.3.0.jar:?]
	at gov.geoplatform.uasdm.service.ProjectManagementService.handleUploadFinish(ProjectManagementService.java:1) ~[uasdm-server-1.3.0.jar:?]
	at gov.geoplatform.uasdm.controller.FileUploadController.lambda$0(FileUploadController.java:185) ~[uasdm-server-1.3.0.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by rrowlands** [comment]
The system is using the user's session while doing chunk merging and other validation tasks (which can take a while), and then it uses the user's session to create a vault file and launch a processing job. If the user logs out (or their session expires) during this process then it causes the workflow task to not be updated, creating a scenario where an upload task is hung. The system has thrown an error but the user will see the job as in progress until the next time the system reboots.

The fix is to grab everything we need from the user's session before chunk merging (such as the user oid), and then to do all processing tasks (such as archive validation) inside the ImageryProcessingJob.

Related #220
